Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-01") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-02") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-03") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-04") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-05") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-06") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-07") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-08") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-09") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-10") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-11") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-12") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-13") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-14") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-15") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-16") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-17") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-18") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-19") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-20") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-21") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-22") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-23") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-24") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-25") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-26") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-27") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-28") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-29") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-30") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-31") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-32") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-33") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-34") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-35") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-36") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-37") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-38") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-39") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-40") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-41") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-42") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-43") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-44") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-45") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-46") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-47") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-48") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-49") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-50") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-51") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-52") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-53") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-54") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-55") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-56") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-57") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-58") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-59") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-60") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-61") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-62") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-63") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-64") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-65") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-66") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-67") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-68") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-69") -MemoryMB 43008
Set-SCVirtualMachine -VM (Get-SCVirtualMachine -VMMServer mehscvmm19.moorfields.nhs.uk -Name "MEHRDS-70") -MemoryMB 43008
